modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "wattledaub"
version = "${version}"
displayName = "Wattle and Daub"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "icon.png"

[[dependencies.wattledaub]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wattledaub]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
